[[plugins]]
repo = 'tpope/vim-markdown'
hook_add = '''
  let g:markdown_fenced_languages = ['html', 'python', 'cpp', 'bash=sh', 'toml']
  '''

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
  syntax enable
  let g:tex_flavor = "latex"
  let g:vimtex_view_general_viewer = 'evince'
'''

# Enabling SyncTeX synchronization support for Vim and Evince through DBus
[[plugins]]
repo = 'peterbjorgensen/sved'
on_ft = ['tex']
hook_add = '''
  nnoremap <F4> :call SVED_Sync()<CR>
'''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
  let g:previm_open_cmd = '/usr/bin/google-chrome'
  '''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'rhysd/vim-grammarous'
hook_add = '''
  let g:grammarous#enable_spell_check=1
  let g:grammarous#disabled_categories = {
          \ '*' : ['PUNCTUATION'],
          \ }
  '''

# toml syntax highlight
[[plugins]]
on_ft = ['toml']
repo = 'cespare/vim-toml'

# Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'


# Twitter on Vim
[[plugins]]
repo = 'twitvim/twitvim'
hook_add = '''
  let twitvim_enable_python = 1
  let twitvim_browser_cmd = 'google-chrome'
  let twitvim_force_ssl = 1
  let twitvim_count = 40
  '''
