[[plugins]]
repo = 'tpope/vim-markdown'
hook_add = '''
  let g:markdown_fenced_languages = ['html', 'python', 'cpp', 'bash=sh', 'toml']
  '''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
  let g:previm_open_cmd = '/mnt/c/Program\ Files\ \(X86\)/Google/Chrome/Application/chrome.exe'
  let g:previm_wsl_mode = 1
  '''

[[plugins]]
repo = 'tyru/open-browser.vim'
