[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:NERDTreeDirArrowExpandable = '>'
  let g:NERDTreeDirArrowExpandable = '▼'
  '''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
hook_add = '''
  let g:airline_theme = 'wombat'
  let g:airline_powerline_fonts = 1
  let g:airline_mode_map = {
          \'n' : 'N',
          \'i' : 'I',
          \'R' : 'R',
          \'c' : 'C',
          \'v' : 'V',
          \'V' : 'V',
          \' ' : 'V',
          \'s' : 'S',
          \'S' : 'S',
          \}
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#branch#enabled = 1
  let g:airline#extensions#whitespace#enabled = 1
  let g:airline_section_z = "\ue0a1:%l/%L: Col:%c"
  '''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  set encoding=utf8
  let g:WebDevIconUnicodeDecorateFolderNodes = 1
  '''

# Show git diff markers in the sign column and stages/previews/undoes hunks and partial hunks
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Molokai Color Scheme for GVim
#[[plugins]]
#repo = 'tomasr/molokai'
#merged = '0'
