[[plugins]]
repo = 'tpope/vim-markdown'
hook_add = '''
  let g:markdown_fenced_languages = ['html', 'python', 'cpp', 'bash=sh', 'toml']
  '''

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
  let g:previm_open_cmd = '/usr/bin/google-chrome'
  '''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'rhysd/vim-grammarous'
hook_add = '''
  let g:grammarous#enable_spell_check=1
  let g:grammarous#disabled_categories = {
          \ '*' : ['PUNCTUATION'],
          \ }
  '''
