[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:NERDTreeDirArrowExpandable = '▶'
  let g:NERDTreeDirArrowExpandable = '▼'
  '''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['/vim-airline-themes']
hook_add = '''
  let g:airline_theme = 'wombat'
  set laststatus=2
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#branch#enabled = 1
  let g:airline#extensions#tabline#fnamemod = ':t'
  let g:airline#extensions#wordcount#enabled = 1
  let g:airline_section_c = '%t'
  let g:airline_section_x = '%{&filetype}'
 ''' 


[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  set encoding=utf8
  let g:WebDevIconUnicodeDecorateFolderNodes = 1
  '''
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_enter = 1
  '''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
