[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add= '''
  let g:deoplete#enable_at_startup = 1
  '''
hook_post_source = '''
  let g:deoplete#omni_patterns = {}
  '''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_i = 1
on_ft = ['python']
hook_source = '''
  let g:deoplete#sources#jedi#statement_length = 0
  let g:deoplete#sources#jedi#short_types = 0
  let g:deoplete#sources#jedi#worker_threads = 2
  '''

[[plugins]]
repo = 'zchee/deoplete-clang'
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang-3.8.so.1'
  let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
  '''
on_ft = ['c', 'cpp', 'cmake']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'dbgx/lldb.nvim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
  let g:previm_open_cmd = 'open -a /mnt/c/"Program Files (x86)"/Google/Chrome/Application/chrome.exe'
  '''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
